/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "systemTypes.h"
#include "asic.h"
#include "hal_gpio.h"
#include "hal_clock.h"
#include "hal_timer.h"

void delay(void)
{
	for (UINT32 j = 0; j < 100; j++)
		for (UINT32 i = 0; i < 1000000; i++);
}


/**
 * Starting main task
 *
 */
int c_main(void)
{
	//
	// Initialize system clock to PLL 100 MHz
	//
	hal_clock_init();

	//
	// Initialize timer
	//
	hal_timer_init();

	//
	// Initialize Port A for LD2
	//
	hal_gpioA_init();

	for(;;)
	{
		// Turn on/off LD2 (PA5)
		hal_gpioA_pin5_toggle();
		for (UINT32 i = 0;  i <= 100000; i++)
			hal_delay_us(1000);
	}

}

